name: Sync main to testing

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  sync:
    uses: projectbluefin/actions/.github/workflows/reusable-sync-branches.yml@eb4c546389f19ad9e42f1af052623de73c620ebb # v1
    permissions:
      contents: write
